### ISSUE TITLE
Deployment procedure: conda create env fails

### ISSUE THREAD

**Issue by foxth** [openforcefield/openff-benchmark#41]
Hi I just tried to set up the environment, but after issueing the commands
conda activate
(base) bibcinews92001 [foxt]% conda env create openforcefield/openff-benchmark-optimization

I get the following error:

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/apps/test/foxt/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 696, in urlopen
        self._prepare_proxy(conn)
      File "/apps/test/foxt/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 964, in _prepare_proxy
        conn.connect()
      File "/apps/test/foxt/anaconda3/lib/python3.7/site-packages/urllib3/connection.py", line 421, in connect
        tls_in_tls=tls_in_tls,
      File "/apps/test/foxt/anaconda3/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 429, in ssl_wrap_socket
        sock, context, tls_in_tls, server_hostname=server_hostname
      File "/apps/test/foxt/anaconda3/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 472, in _ssl_wrap_socket_impl
        return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
      File "/apps/test/foxt/anaconda3/lib/python3.7/ssl.py", line 423, in wrap_socket
        session=session
      File "/apps/test/foxt/anaconda3/lib/python3.7/ssl.py", line 870, in _create
        self.do_handshake()
      File "/apps/test/foxt/anaconda3/lib/python3.7/ssl.py", line 1139, in do_handshake
        self._sslobj.do_handshake()
    ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/apps/test/foxt/anaconda3/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
        timeout=timeout
      File "/apps/test/foxt/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 756, in urlopen
        method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
      File "/apps/test/foxt/anaconda3/lib/python3.7/site-packages/urllib3/util/retry.py", line 573, in increment
        raise MaxRetryError(_pool, url, error or ResponseError(cause))
    urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.anaconda.org', port=443): Max retries exceeded with url: /package/openforcefield/openff-benchmark-optimization (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)')))
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/apps/test/foxt/anaconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/apps/test/foxt/anaconda3/lib/python3.7/site-packages/conda_env/cli/main.py", line 80, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/apps/test/foxt/anaconda3/lib/python3.7/site-packages/conda_env/cli/main_create.py", line 87, in execute
        spec = specs.detect(name=name, filename=filename, directory=os.getcwd())
      File "/apps/test/foxt/anaconda3/lib/python3.7/site-packages/conda_env/specs/__init__.py", line 43, in detect
        if spec.can_handle():
      File "/apps/test/foxt/anaconda3/lib/python3.7/site-packages/conda_env/specs/binstar.py", line 45, in can_handle
        result = self._can_handle()
      File "/apps/test/foxt/anaconda3/lib/python3.7/site-packages/conda_env/specs/binstar.py", line 60, in _can_handle
        return self.package is not None and self.valid_package()
      File "/apps/test/foxt/anaconda3/lib/python3.7/site-packages/conda_env/specs/binstar.py", line 114, in package
        self._package = self.binstar.package(self.username, self.packagename)
      File "/apps/test/foxt/anaconda3/lib/python3.7/site-packages/binstar_client/__init__.py", line 301, in package
        res = self.session.get(url)
      File "/apps/test/foxt/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 555, in get
        return self.request('GET', url, **kwargs)
      File "/apps/test/foxt/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 542, in request
        resp = self.send(prep, **send_kwargs)
      File "/apps/test/foxt/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 655, in send
        r = adapter.send(request, **kwargs)
      File "/apps/test/foxt/anaconda3/lib/python3.7/site-packages/requests/adapters.py", line 514, in send
        raise SSLError(e, request=request)
    requests.exceptions.SSLError: HTTPSConnectionPool(host='api.anaconda.org', port=443): Max retries exceeded with url: /package/openforcefield/openff-benchmark-optimization (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)')))

`$ /apps/test/foxt/anaconda3/bin/conda-env create openforcefield/openff-benchmark-optimization`

  environment variables:
                 CIO_TEST=<not set>
                CLASSPATH=/apps/prod/COMPCHEM/chemaxon/MarvinBeans/lib/MarvinBeans.jar
  CONDA_AUTO_UPDATE_CONDA=false
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/apps/test/foxt/anaconda3/bin/conda
             CONDA_PREFIX=/apps/test/foxt/anaconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/apps/test/foxt/anaconda3/bin/python
               CONDA_ROOT=/apps/test/foxt/anaconda3
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
       DRMAA_LIBRARY_PATH=/opt/sge/lib//libdrmaa.so
                FTP_PROXY=<set>
              HTTPS_PROXY=<set>
               HTTP_PROXY=<set>
          LD_LIBRARY_PATH=/apps/prod/amber/amber18-18_sl7/lib:/usr/local/cuda/lib64:/apps/prod/a
                          mber/amber18-18_sl7/lib:/apps/prod/COMPCHEM/openeye/openeye_2018/java/
                          libs/Linux-x64/:/apps/prod/COMPCHEM/gaussian/g09/g09/bsd:/apps/prod/CO
                          MPCHEM/gaussian/g09/g09/local:/apps/prod/COMPCHEM/gaussian/g09/g09/ext
                          ras:/apps/prod/COMPCHEM/gaussian/g09/g09::/opt/slurm/prod/lib64:/opt/s
                          lurm/prod/lib64:/apps/prod/COMPCHEM/gaussian/g09/gv/lib
              LD_RUN_PATH=:/opt/slurm/prod/lib64
                  MANPATH=/opt/sge/man:/apps/prod/COMPCHEM/gaussian/g09/g09/bsd:/opt/sge/man:/us
                          r/share/lmod/lmod/share/man:/opt/sge/man::/opt/slurm/prod/share/man:/o
                          pt/slurm/prod/share/man:/apps/prod/COMPCHEM/cresset/blaze/current/xed/
                          man
               MODULEPATH=/usr/share/modulefiles/Linux:/usr/share/modulefiles/Core:/usr/share/lm
                          od/lmod/modulefiles/Core
                 NO_PROXY=<set>
                     PATH=/apps/test/foxt/anaconda3/bin:/apps/test/foxt/anaconda3/bin:/apps/test
                          /foxt/anaconda3/condabin:/apps/test/foxt/anaconda3/bin:/apps/test/foxt
                          /anaconda3/bin:/apps/test/foxt/anaconda3/bin:/apps/test/foxt/anaconda3
                          /bin:/apps/prod/amber/amber18-18_sl7/bin:/opt/slurm/prod/bin:/apps/pro
                          d/amber/amber18-18_sl7/bin:/apps/test/COMPCHEM/DivConDiscoverySuite/Di
                          vConDiscoverySuite/bin:/apps/prod/ccg/moe/bin:/home/foxt/AMBER/ti_scri
                          pts:/home/foxt/bin:/apps/test/foxt/anaconda3/bin:/home/foxt/bin:/apps/
                          prod/amber/amber18-18_sl7/bin:/apps/prod/COMPCHEM/compchem/vim/current
                          /bin:/apps/prod/COMPCHEM/compchem/vim/bin:/opt/sge/bin:/opt/sge/bin/lx
                          -amd64:/apps/prod/COMPCHEM/knime/bin:/apps/prod/COMPCHEM/schrodinger/c
                          urrent:/apps/prod/COMPCHEM/ccdc/cambridge_2020.0.1/Discovery_2020/bin:
                          /apps/prod/COMPCHEM/ccdc/cambridge_2020.0.1/CSD_2020/bin:/apps/prod/CO
                          MPCHEM/alvaDesc/bin:/opt/sge/bin:/opt/sge/bin/lx-
                          amd64:/usr/lib64/qt-3.3/bin:/opt/sge/bin:/opt/sge/bin/lx-amd64:/usr/lo
                          cal/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/slurm/prod/bin:/o
                          pt/singularity/bin:/opt/slurm/prod/bin:/opt/singularity/bin:/apps/prod
                          /COMPCHEM/compchem/bin:/apps/prod/COMPCHEM/gaussian/g09/g09/bsd:/apps/
                          prod/COMPCHEM/gaussian/g09/g09/local:/apps/prod/COMPCHEM/gaussian/g09/
                          g09/extras:/apps/prod/COMPCHEM/gaussian/g09/g09:/home/foxt/bin/perlscr
                          ipts:/home/foxt/AMBER/ti_scripts
               PYTHONPATH=/apps/prod/amber/amber18-18_sl7/lib/python2.7/site-
                          packages:/apps/prod/amber/amber18-18_sl7/lib/python2.7/site-packages
           QT_PLUGIN_PATH=/usr/lib64/kde4/plugins:/usr/lib/kde4/plugins
               RASMOLPATH=/apps/prod/COMPCHEM/cresset/blaze/current/xed/xedman
       REQUESTS_CA_BUNDLE=<not set>
                   R_PATH=/apps/prod/COMPCHEM/R/R-current
            SSL_CERT_FILE=<not set>
                ftp_proxy=<set>
               http_proxy=<set>
              https_proxy=<set>
                 no_proxy=<set>

     active environment : base
    active env location : /apps/test/foxt/anaconda3
            shell level : 1
       user config file : /home/foxt/.condarc
 populated config files : /home/foxt/.condarc
          conda version : 4.9.2
    conda-build version : 3.21.4
         python version : 3.7.9.final.0
       virtual packages : __cuda=10.0=0
                          __glibc=2.17=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /apps/test/foxt/anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/omnia/linux-64
                          https://conda.anaconda.org/omnia/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /apps/test/foxt/anaconda3/pkgs
                          /home/foxt/.conda/pkgs
       envs directories : /apps/test/foxt/anaconda3/envs
                          /home/foxt/.conda/envs
               platform : linux-64
             user-agent : conda/4.9.2 requests/2.25.1 CPython/3.7.9 Linux/3.10.0-514.6.1.el7.x86_64 rhel/7.4 glibc/2.17
                UID:GID : 1189:3220
             netrc file : None
           offline mode : False

An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/apps/test/foxt/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 696, in urlopen
        self._prepare_proxy(conn)
      File "/apps/test/foxt/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 964, in _prepare_proxy
        conn.connect()
      File "/apps/test/foxt/anaconda3/lib/python3.7/site-packages/urllib3/connection.py", line 421, in connect
        tls_in_tls=tls_in_tls,
      File "/apps/test/foxt/anaconda3/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 429, in ssl_wrap_socket
        sock, context, tls_in_tls, server_hostname=server_hostname
      File "/apps/test/foxt/anaconda3/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 472, in _ssl_wrap_socket_impl
        return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
      File "/apps/test/foxt/anaconda3/lib/python3.7/ssl.py", line 423, in wrap_socket
        session=session
      File "/apps/test/foxt/anaconda3/lib/python3.7/ssl.py", line 870, in _create
        self.do_handshake()
      File "/apps/test/foxt/anaconda3/lib/python3.7/ssl.py", line 1139, in do_handshake
        self._sslobj.do_handshake()
    ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/apps/test/foxt/anaconda3/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
        timeout=timeout
      File "/apps/test/foxt/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 756, in urlopen
        method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
      File "/apps/test/foxt/anaconda3/lib/python3.7/site-packages/urllib3/util/retry.py", line 573, in increment
        raise MaxRetryError(_pool, url, error or ResponseError(cause))
    urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.anaconda.org', port=443): Max retries exceeded with url: /package/openforcefield/openff-benchmark-optimization (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)')))
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/apps/test/foxt/anaconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/apps/test/foxt/anaconda3/lib/python3.7/site-packages/conda_env/cli/main.py", line 80, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/apps/test/foxt/anaconda3/lib/python3.7/site-packages/conda_env/cli/main_create.py", line 87, in execute
        spec = specs.detect(name=name, filename=filename, directory=os.getcwd())
      File "/apps/test/foxt/anaconda3/lib/python3.7/site-packages/conda_env/specs/__init__.py", line 43, in detect
        if spec.can_handle():
      File "/apps/test/foxt/anaconda3/lib/python3.7/site-packages/conda_env/specs/binstar.py", line 45, in can_handle
        result = self._can_handle()
      File "/apps/test/foxt/anaconda3/lib/python3.7/site-packages/conda_env/specs/binstar.py", line 60, in _can_handle
        return self.package is not None and self.valid_package()
      File "/apps/test/foxt/anaconda3/lib/python3.7/site-packages/conda_env/specs/binstar.py", line 114, in package
        self._package = self.binstar.package(self.username, self.packagename)
      File "/apps/test/foxt/anaconda3/lib/python3.7/site-packages/binstar_client/__init__.py", line 301, in package
        res = self.session.get(url)
      File "/apps/test/foxt/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 555, in get
        return self.request('GET', url, **kwargs)
      File "/apps/test/foxt/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 542, in request
        resp = self.send(prep, **send_kwargs)
      File "/apps/test/foxt/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 655, in send
        r = adapter.send(request, **kwargs)
      File "/apps/test/foxt/anaconda3/lib/python3.7/site-packages/requests/adapters.py", line 514, in send
        raise SSLError(e, request=request)
    requests.exceptions.SSLError: HTTPSConnectionPool(host='api.anaconda.org', port=443): Max retries exceeded with url: /package/openforcefield/openff-benchmark-optimization (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)')))

`$ /apps/test/foxt/anaconda3/bin/conda-env create openforcefield/openff-benchmark-optimization`

  environment variables:
                 CIO_TEST=<not set>
                CLASSPATH=/apps/prod/COMPCHEM/chemaxon/MarvinBeans/lib/MarvinBeans.jar
  CONDA_AUTO_UPDATE_CONDA=false
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/apps/test/foxt/anaconda3/bin/conda
             CONDA_PREFIX=/apps/test/foxt/anaconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/apps/test/foxt/anaconda3/bin/python
               CONDA_ROOT=/apps/test/foxt/anaconda3
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
       DRMAA_LIBRARY_PATH=/opt/sge/lib//libdrmaa.so
                FTP_PROXY=<set>
              HTTPS_PROXY=<set>
               HTTP_PROXY=<set>
          LD_LIBRARY_PATH=/apps/prod/amber/amber18-18_sl7/lib:/usr/local/cuda/lib64:/apps/prod/a
                          mber/amber18-18_sl7/lib:/apps/prod/COMPCHEM/openeye/openeye_2018/java/
                          libs/Linux-x64/:/apps/prod/COMPCHEM/gaussian/g09/g09/bsd:/apps/prod/CO
                          MPCHEM/gaussian/g09/g09/local:/apps/prod/COMPCHEM/gaussian/g09/g09/ext
                          ras:/apps/prod/COMPCHEM/gaussian/g09/g09::/opt/slurm/prod/lib64:/opt/s
                          lurm/prod/lib64:/apps/prod/COMPCHEM/gaussian/g09/gv/lib
              LD_RUN_PATH=:/opt/slurm/prod/lib64
                  MANPATH=/opt/sge/man:/apps/prod/COMPCHEM/gaussian/g09/g09/bsd:/opt/sge/man:/us
                          r/share/lmod/lmod/share/man:/opt/sge/man::/opt/slurm/prod/share/man:/o
                          pt/slurm/prod/share/man:/apps/prod/COMPCHEM/cresset/blaze/current/xed/
                          man
               MODULEPATH=/usr/share/modulefiles/Linux:/usr/share/modulefiles/Core:/usr/share/lm
                          od/lmod/modulefiles/Core
                 NO_PROXY=<set>
                     PATH=/apps/test/foxt/anaconda3/bin:/apps/test/foxt/anaconda3/bin:/apps/test
                          /foxt/anaconda3/condabin:/apps/test/foxt/anaconda3/bin:/apps/test/foxt
                          /anaconda3/bin:/apps/test/foxt/anaconda3/bin:/apps/test/foxt/anaconda3
                          /bin:/apps/prod/amber/amber18-18_sl7/bin:/opt/slurm/prod/bin:/apps/pro
                          d/amber/amber18-18_sl7/bin:/apps/test/COMPCHEM/DivConDiscoverySuite/Di
                          vConDiscoverySuite/bin:/apps/prod/ccg/moe/bin:/home/foxt/AMBER/ti_scri
                          pts:/home/foxt/bin:/apps/test/foxt/anaconda3/bin:/home/foxt/bin:/apps/
                          prod/amber/amber18-18_sl7/bin:/apps/prod/COMPCHEM/compchem/vim/current
                          /bin:/apps/prod/COMPCHEM/compchem/vim/bin:/opt/sge/bin:/opt/sge/bin/lx
                          -amd64:/apps/prod/COMPCHEM/knime/bin:/apps/prod/COMPCHEM/schrodinger/c
                          urrent:/apps/prod/COMPCHEM/ccdc/cambridge_2020.0.1/Discovery_2020/bin:
                          /apps/prod/COMPCHEM/ccdc/cambridge_2020.0.1/CSD_2020/bin:/apps/prod/CO
                          MPCHEM/alvaDesc/bin:/opt/sge/bin:/opt/sge/bin/lx-
                          amd64:/usr/lib64/qt-3.3/bin:/opt/sge/bin:/opt/sge/bin/lx-amd64:/usr/lo
                          cal/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/slurm/prod/bin:/o
                          pt/singularity/bin:/opt/slurm/prod/bin:/opt/singularity/bin:/apps/prod
                          /COMPCHEM/compchem/bin:/apps/prod/COMPCHEM/gaussian/g09/g09/bsd:/apps/
                          prod/COMPCHEM/gaussian/g09/g09/local:/apps/prod/COMPCHEM/gaussian/g09/
                          g09/extras:/apps/prod/COMPCHEM/gaussian/g09/g09:/home/foxt/bin/perlscr
                          ipts:/home/foxt/AMBER/ti_scripts
               PYTHONPATH=/apps/prod/amber/amber18-18_sl7/lib/python2.7/site-
                          packages:/apps/prod/amber/amber18-18_sl7/lib/python2.7/site-packages
           QT_PLUGIN_PATH=/usr/lib64/kde4/plugins:/usr/lib/kde4/plugins
               RASMOLPATH=/apps/prod/COMPCHEM/cresset/blaze/current/xed/xedman
       REQUESTS_CA_BUNDLE=<not set>
                   R_PATH=/apps/prod/COMPCHEM/R/R-current
            SSL_CERT_FILE=<not set>
                ftp_proxy=<set>
               http_proxy=<set>
              https_proxy=<set>
                 no_proxy=<set>

     active environment : base
    active env location : /apps/test/foxt/anaconda3
            shell level : 1
       user config file : /home/foxt/.condarc
 populated config files : /home/foxt/.condarc
          conda version : 4.9.2
    conda-build version : 3.21.4
         python version : 3.7.9.final.0
       virtual packages : __cuda=10.0=0
                          __glibc=2.17=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /apps/test/foxt/anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/omnia/linux-64
                          https://conda.anaconda.org/omnia/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /apps/test/foxt/anaconda3/pkgs
                          /home/foxt/.conda/pkgs
       envs directories : /apps/test/foxt/anaconda3/envs
                          /home/foxt/.conda/envs
               platform : linux-64
             user-agent : conda/4.9.2 requests/2.25.1 CPython/3.7.9 Linux/3.10.0-514.6.1.el7.x86_64 rhel/7.4 glibc/2.17
                UID:GID : 1189:3220
             netrc file : None
           offline mode : False

An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?

I have tried
conda config --set ssl_verify false

but this didnt change things.

I checked and I can access the outside world with conda and e.g. update packages...

Any idea?

Best,
Th.

**Comment by j-wags** [comment]
Thanks for the detailed report. I'm unable to reproduce this. My hypotheses at this time are:
* Maybe it was an intermittent issue with the server. Could you try again now that some time has passed?
* Are the known keys out of date? Perhaps try running `conda update --all`

**Comment by ircraig** [comment]
I get the same error. I tried running `conda update --all` but it didn't make a difference. Is there anything else I should try?

**Comment by foxth** [comment]
Today it worked. 
First did a update --all, then conda env create. Then the installation ran through and I can activate the environment.

**Comment by j-wags** [comment]
@ircraig As a fall-back option, you could try downloading the single-file installer from the `Downloads`/`Assets` section of the most recent release [on the openff-benchmark github repository](https://github.com/openforcefield/openff-benchmark/tags) (it's the 1.1GB file beginning with `ubuntu...`). This is linux-only, and contains static copies of all the dependencies so installation doesn't require an internet connection after the initial download. Instructions for installing from that file are [here](https://openforcefield.atlassian.net/wiki/spaces/PS/pages/873922575/Deployment+Procedure#Installation-using-a-single-file-installer)

**Comment by ircraig** [comment]
OK, thanks. I'll give the single-file installer a try.

**Comment by foxth** [comment]
Hi Jeff,

 

just want to report that I successfully ran 10 test compounds through the pipeline using option C. Very swift, great work at your end!! How final is the report compare-forcefield part? Here I got a lot of warnings, but the csvfiles were produced.

 

What I do get: in all FF csvfiles I have one conformation (always the same) where the tfd is missing. What is the meaning of this? The compound in itself looks harmless CC(N)C(=O)OC, and the json files look normal, the sdfile has a initial and final energy tag. I guess I can send you the files if this helps...

 

Best,

Th.

 
 

Gesendet: Montag, 25. Januar 2021 um 19:35 Uhr
Von: "Jeff Wagner" <notifications@github.com>
An: "openforcefield/openff-benchmark" <openff-benchmark@noreply.github.com>
Cc: "foxth" <Thomas.fox@gmx.net>, "Author" <author@noreply.github.com>
Betreff: Re: [openforcefield/openff-benchmark] Deployment procedure: conda create env fails (#41)


 

Thanks for the detailed report. I'm unable to reproduce this. My hypotheses at this time are:


	Maybe it was an intermittent issue with the server. Could you try again now that some time has passed?
	Are the known keys out of date? Perhaps try running conda update --all

**Comment by j-wags** [comment]
Hi @foxth, 

The force field comparison code is currently preliminary -- The big push at this stage is to ensure that everyone can use their in-house computing resources to complete the QM jobs, since that may take > 1 month for large datasets. 

Regarding the missing TFD, please do send us the underlying data files You should be able to zip the outputs into a `zip` or `tar.gz` file and attach it when replying to this message (you'll have to use github for file attachments, not email). Tagging @dfhahn on this since he's more familiar with the analysis code.

**Comment by foxth** [comment]
Hi Jeff and David,

 

here the input and output files for the compound for which not all info ends up in the final csv-file. One thing I noticed only now is that your procedure originally created 2 conformations, but only one was successfully calculated - the second one fails with a stereocenter error. Hm.

 

Anyways, please have a look, I cannot exclude that I did sth stupid, although your procedure seemed pretty foolproof to me...

 

Best,

Th.

 
 

Gesendet: Mittwoch, 27. Januar 2021 um 18:40 Uhr
Von: "Jeff Wagner" <notifications@github.com>
An: "openforcefield/openff-benchmark" <openff-benchmark@noreply.github.com>
Cc: "foxth" <Thomas.fox@gmx.net>, "Mention" <mention@noreply.github.com>
Betreff: Re: [openforcefield/openff-benchmark] Deployment procedure: conda create env fails (#41)


 

Hi @foxth,

The force field comparison code is currently preliminary -- The big push at this stage is to ensure that everyone can use their in-house computing resources to complete the QM jobs, since that may take > 1 month for large datasets.

Regarding the missing TFD, please do send us the underlying data files You should be able to zip the outputs into a zip or tar.gz file and attach it when replying to this message (you'll have to use github for file attachments, not email). Tagging @dfhahn on this since he's more familiar with the analysis code.

**Comment by dotsdl** [comment]
> here the input and output files for the compound for which not all info ends up in the final csv-file. One thing I noticed only now is that your procedure originally created 2 conformations, but only one was successfully calculated - the second one fails with a stereocenter error. Hm.

Hi @foxth, the file didn't attach because your email gets posted as a comment on this issue. However, I'll note that this failure was for an earlier iteration of the protocol software and it may now be a moot point.

We're still interested in this failure mode, however, since it is odd that one conformer for a molecule failed with a stereocenter error while another succeeded. If you're able to find the failed conformer's SDF file, can you post the contents here (assuming this is a **publicly-shareable** compound)?
