### ISSUE TITLE
`openff-benchmark` CLI help broken by logging config

### ISSUE THREAD

**Issue by dotsdl** [openforcefield/openff-benchmark#54]
The [logging configuration attempting to use `sys.argv`](https://github.com/openforcefield/openff-benchmark/blob/e7b81a073466f7a4782c91cc9a427910ac1bc471/openff/benchmark/cli.py#L28-L30) as the filename breaks the CLI when used without a 2-deep subcommand:

```
# broken
$ openff-benchmark
Traceback (most recent call last):
  File "/home/david/.conda/envs/openff-benchmark-optimization/bin/openff-benchmark", line 7, in <module>
    from openff.benchmark.cli import cli
  File "/home/david/.conda/envs/openff-benchmark-optimization/lib/python3.7/site-packages/openff/benchmark/cli.py", line 28, in <module>
    logging.basicConfig(filename=f'{sys.argv[2]}.log',
IndexError: list index out of range
```
```
# broken
$ openff-benchmark optimize
Traceback (most recent call last):
  File "/home/david/.conda/envs/openff-benchmark-optimization/bin/openff-benchmark", line 7, in <module>
    from openff.benchmark.cli import cli
  File "/home/david/.conda/envs/openff-benchmark-optimization/lib/python3.7/site-packages/openff/benchmark/cli.py", line 28, in <module>
    logging.basicConfig(filename=f'{sys.argv[2]}.log',
IndexError: list index out of range
```
```
# works fine
$ openff-benchmark optimize execute
Usage: openff-benchmark optimize execute [OPTIONS] [INPUT_PATHS]...
Try 'openff-benchmark optimize execute --help' for help.

Error: Missing option '-s' / '--season'.
```

Will address with conditional logic.

**Comment by dotsdl** [comment]
Closed by #55.
